name: grabby_babby_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  dartz: ^0.10.1
  universal_html: ^2.2.4
  pretty_dio_logger: ^1.4.0
  socket_io_client: ^3.0.2
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  shimmer: ^3.0.0
  collection: ^1.19.0
  go_router: ^14.8.0
  flutter_screenutil: ^5.9.3
  data_table_2: ^2.5.18
  fl_chart: ^0.70.2
  http: ^1.3.0
  file_picker: ^9.0.2
  get_storage: ^2.1.1
  gap: ^3.0.1
  calendar_date_picker2: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo.ttf
