class AppImages {
  AppImages._();
  static const baseDir = 'assets/images';
  static const loginBg = '$baseDir/login_bg.png';
  static const logo = '$baseDir/logo.png';
  static const dashboard = '$baseDir/dashboard.png';
  static const users = '$baseDir/users.png';
  static const transactions = '$baseDir/transaction.png';
  static const analytics = '$baseDir/analytics.png';
  static const contentManagement = '$baseDir/content.png';
  static const notifications = '$baseDir/notifications.png';
  static const settings = '$baseDir/settings.png';
  static const supportManagement = '$baseDir/support.png';
  static const logout = '$baseDir/logout.png';
  static const appBarNotification = '$baseDir/app_bar_notification.png';
  static const dummyUser = '$baseDir/dummy_user.png';
  static const totalUsers = '$baseDir/total_users.png';
  static const pendingApproval = '$baseDir/pending_approval.png';
  static const businessSellers = '$baseDir/business_sellers.png';
  static const buyers = '$baseDir/buyers.png';
  static const sellers = '$baseDir/sellers.png';
  static const coverImage = '$baseDir/cover.png';
  static const productImage1 = '$baseDir/product1.png';
  static const productImage2 = '$baseDir/product2.png';
  static const productImage3 = '$baseDir/product3.png';
  static const productImage4 = '$baseDir/product4.png';
  static const tick = '$baseDir/tick.png';
  static const lock = '$baseDir/lock.png';
  static const lighting = "$baseDir/lighting.png";
  static const gallery = "$baseDir/gallery.png";
  static const send = "$baseDir/send.png";
  static const file = "$baseDir/file.png";
  static const emoji = "$baseDir/emoji.png";
  static const filter = "$baseDir/filter.png";
}
