name: Flutter Web Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.4'
        dart-version: '3.6.2'
        channel: 'stable'
    
    - name: Get dependencies
      run: flutter pub get
    
    - name: Build Flutter Web
      run: flutter build web --release
    
    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: 217.65.145.67
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "build/web/*"
        target: "/var/www/Frontend/"
        strip_components: 1
    
    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
        host: 217.65.145.67
        username: root
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          sudo systemctl restart nginx